### ISSUE TITLE
Importing the plug-ins results in tow projects with identical resources

### ISSUE THREAD

**Issue by markejfmunro** [Vantiq/Blueprints#15]
![image](https://user-images.githubusercontent.com/10976970/85983865-2737c280-b9e0-11ea-95dc-2d3db4ca97c1.png)

AppCentrakRTLS;

![image](https://user-images.githubusercontent.com/10976970/85983911-3cacec80-b9e0-11ea-9390-22e2d9b897f0.png)

CentrakRTLS

![image](https://user-images.githubusercontent.com/10976970/85983956-4d5d6280-b9e0-11ea-94da-6dec3447dc25.png)

**Comment by JakeSchmitz** [comment]
Please file issues against the Vantiq/Blueprints repo, not the Vantiq/vantiq-blueprints repo. The latter is only for the zip files used to import in the UI. All issues should be reported against this repo, where the code lives.
