### ISSUE TITLE
Field Service Management collab.notifyCustomer: Unable to parse duration string

### ISSUE THREAD

**Issue by MarcelRParcs** [Vantiq/Blueprints#5]
Hello everyone,

when i insert a new workorder and schedule the estimated arrival time in the mobile app, the procedure [collab.notifyCustomer](https://github.com/Vantiq/Blueprints/blob/master/Field%20Service%20Management/procedures/collab_notifyCustomer.vail) throws an error:
_Unable to parse duration string '3600000'. Expected number followed by time unit.Execution Start Time: 2019-01-18 19:25:50.401 Execution End Time: 2019-01-18 19:25:50.401 Elapsed Time: 0ms 
This procedure failed during execution. The last known contents of the scratchpad are shown, and the failing statement has been highlighted.
Code: UnknownMessage: Unable to parse duration string '3600000'. 
Expected number followed by time unit._ 

The failing statement is:
`arrivaltime = arrivaltime.plusMillis(stringToInterval(offset * 1000))`

When i remove the 'stringToInterval' function the program continues without an error, although I am not exactly sure if the procedure still works as intended. 
The new line:
`arrivaltime = arrivaltime.plusMillis(offset * 1000)`

Best regards,
Marcel

**Comment by bruden01** [comment]
That's odd.  `stringToInterval`  basically takes a string like "3 seconds" and returns an integer.  So "3 seconds" becomed 3000..

Its possible at one point this was hardcoded but this code woudn't work as your offset isn't actually a valid interval.  its probaly just 360 ergo ` Unable to parse duration string '3600000'.`

So your solution is likely correct and we'll adjust it in the blueprint.  

Thank you.

**Comment by pburma** [comment]
Made the correction. Both positive and negative offsets (+7 GMT, -7 GMT) should work correctly now where as before just the negative numbers would have worked.
